# 线上配置文件
# @author <a href="https://github.com/granvilledon">granvilledon</a>

spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://gz-cynosdbmysql-grp-rmjfqvef.sql.tencentcdb.com:22137/user_center?useSSL=false
    username: root
    password: 1234zxcv!
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0

